blog_blog_homepage:
    path:     /
    defaults: { _controller: BlogBlogBundle:Page:index }

BlogBlogBundle_about:
    path:   /about
    defaults: { _controller: BlogBlogBundle:Page:about }
    requirements:
         methods:  GET

BlogBlogBundle_contact:
    path:   /contact
    defaults: { _controller: BlogBlogBundle:Page:contact }
    requirements:
         methods:  GET|POST